id: P008153
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:04:54.780474
source_metadata:
  id: bdr:W1CZ1105
  title: ཞལ་གདམས་གནད་ཀྱི་ཟླ་ཟེར་
  author: ''
  volumes:
    e2cc39ff404a46cfbb2adeace816a39e:
      image_group_id: I1CZ1372
      title: Volume 1 of zhal gdams gnad kyi zla zer
      volume_number: 1
      total_pages: 28
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
