id: P008153
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1105
  title: ཞལ་གདམས་གནད་ཀྱི་ཟླ་ཟེར་
  author: ''
  volumes:
    58357b40e1de4ca9bf50b37ad29a2415:
      image_group_id: I1CZ1372
      title: ''
      volume_number: 1
      total_pages: 28
ebook_metadata:
  title: ཞལ་གདམས་གནད་ཀྱི་ཟླ་ཟེར་
  author: ''
  sku: P008153
  cover: cover.jpg
  layers:
  - pagination
