id: IFA7AA0CE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T10:21:49+00:00'
last_modified: '2022-06-09T04:52:23.634269+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1105
  title: ཞལ་གདམས་གནད་ཀྱི་ཟླ་ཟེར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    168A:
      image_group_id: I1CZ1372
      title: Volume 1 of zhal gdams gnad kyi zla zer
      total_pages: 28
      order: 1
      base_file: 168A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
